package Enum;

public enum Operacao {
    CADASTRAR_AVIAO,
    REMOVER_AVIAO,
    VENDER_PASSAGEM,
    CANCELAR_PASSAGEM,
    INSERIR_FILA_COMUM,
    INSERIR_FILA_PRIORIDADE,
    EMBARCAR_PASSAGEIRO
}
